services:
  laundress-backend:
    image: laundress-backend@latest
    build:
      dockerfile: laundress-backend.Dockerfile
      context: ../../../
  laundress-frontend:
    image: laundress-frontend@latest
    build:
      dockerfile: laundress-frontend.Dockerfile
      context: ../../../
    expose:
      - 3000
    ports:
      - 3000
    